using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;


public enum P
{
    // Activators
    AltMovon,
    FastBackRoton,
    SplitonStealon,
    Shuffleton,
    SCSinkon,
    PExchangon,
    SpaceConsumon,
    BackGciBudon,
    GForBudon,
    ForBudon,
    L2Rotaton,
    R2Rotaton,
    AnothDoubleton,
    BackBudon,
    JCeenon,
    LKillon18,
    FreeConsumon,
    Spliton,
    RightRotaton,
    LeftRotaton,
    Movon,
    VoidConsumon,
    CellConsumon,
    Injecton,
    Rebirthon,
    Pushon,
    Swapon,
    Killon,
    Suicidon,
    Explodon,
    Equalon,
    EcKillon,
    Sprayon,
    Navigon0,
    Navigon1,
    Navigon2,
    Navigon3,
    Navigon4,
    Navigon5,
    AssGearon,
    KissGearon,
    EnerGivon,
    Accumuton,
    NavigonB,
    Backwardon,
    Fuson,
    Spamon,
    Doubleton,
    // Transproteins
    HEnTMovon,
    MASuron,
    FCWaston,
    TransNavigonB,
    TransBetaRestarton12,
    TransRestarton12,
    MaklUtiliton,
    HEBomUtiliton,
    FCExpUtiliton,
    SuiNExplUtiliton,
    InjSPrionUtiliton,
    FreConUtiliton,
    TransRotaton,
    TransMovon,
    TransInjecton,
    TransSwapon,
    // BetaActivators
    MAFon,
    FSpliton,
    InjExpon,
    SurRoton,
    InjRevoluton,
    JCActivon,
    LightSpeedon,
    FCPlagStarton,
    EqBomberon,
    MHungeron,
    PBomberon,
    // Trojans
    SPrPrion,
    AlphaHolyGrailon,
    BetaHolyGrailon,
    InjDeathon,
    PopCornon,
    InjectIngibiton,
    FreeconsumExplodon,
    SplitDeenergon,
    MoveAcceleron,
    SplitPrion,
    ShiftIngibiton,
    InjSPrion,
    // T-Wanderers
    Nothingon,
    Maklayon,
    FCPlaguon,
    // Regulators
    Conservon,
    LowEnergivon,
    OldEnergivon,
    YoungEnergivon,
    // TransRegulators
    SurMovon,
    KSurVCon,
    LeDeplaguon,
    SurInjAHGon,
    FCDeshifton,
    HighEnDeathon,
    HighEnSPRegulon,
    KilOldExTranson,
    HighEnBomberon,
    // Shifters
    HeritShifton,
    FC6Restarton,
    TShifton,
    HalfShifton,
    SmoothAgeDeRestarton,
    SmoothAgeRestarton,
    Restarton6B,
    Restarton12,
    NavRestarton0,
    NavRestarton1,
    NavRestarton2,
    NavRestarton3,
    NavRestarton4,
    NavRestarton5,
    NavRestartonB,
    NavRestartonAB,
    YoungRestarton,
    OldRestarton,
    OnceRestarton,
    OnceDeRestarton,
    LowEnRestarton,
    HighEnRestarton,
    Restarton,
    DoubleShifton,
    // Fabricators
    PFabricaton,
    JCFabricaton,
    FCFabricaton,
    FusFabricaton,
    YoungEGFabricaton,
    MovFabricaton,
    // Commands
    FCImidSprayon,
    KSMon,
    FcWVcoon,
    ImidfromFCFuson,
    GammaHolyGrailon,
    ImidSprayon,
    FullAheadon,
    // ===
    Last
}
